"""add detail column to audit_logs

Revision ID: 40db1b6fa1a5
Revises: 6a8b0ac996ca
Create Date: 2025-07-06 06:27:54.464372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40db1b6fa1a5'
down_revision: Union[str, Sequence[str], None] = '6a8b0ac996ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'audit_logs',
        sa.Column('detail', sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'detail')
    # ### end Alembic commands ###
